<template>
  <div class="w-2/3 m-auto py-40">
    <b>Privacy Policy</b><br><br>
    Effective Date: 09/01/2020
    Here you will find and understand how and why Sandragon Inc. (“Sandragon,” “we” or “us”) collects, uses, and shares information about you when you use our websites, mobile apps, extensions, and other online products and services (collectively, the "services") or when you otherwise interact with us or receive a communication from us. This Privacy Policy applies to all Sandragon Services.
   <br><br><b>What we Collect</b><br><br>
    Information You Provide to Us
    We collect Information you provide to us when using our services such as:
    Account Information: Usernames, emails, passwords, and account settings may be stored to facilitate your login and use of our services. Your username is made public and does not have to relate to any identifying information about you.
    Submitted Content: When you publish any text, image, video or link, that content is stored for the intended receivers whether it be public or private between users.
    Affirmative acts: We store data on your actions such as voting, reporting, saving content.
    Transactional Services: You may purchase digital items or other goods using the services. We use a third-party payment provider to process payments on the Services. We may receive information associated with your payment information, such as billing address and transaction information, but we do not directly store payment information on the Services.
    Other: if you choose to contact us, you may choose to provide additional information directly to us. This includes contact information, phone number, or form data such as a job application.
    Information We Automatically Collect
    When you access our services, we may automatically collect some data from you, including:
    Usage data: We may log information when you access and use services. This may include your IP address, user-agent string, browser type, operating system, referral URLs, device information, the requested URL, and search terms.
    Cookies and similar technologies: We may receive information from cookies, which are pieces of data your browser stores and sends back to us when making requests, and similar technologies. We use this information to improve your experience, understand user activity, personalize content and advertisements, and improve the quality of our services.
    Location information: We may receive and process information about your location. For example, with your consent, we may collect information about the specific location of your mobile device (for example, by using GPS or Bluetooth). We may also receive location information from you when you choose to share such information on our services, including by associating your content with a location, or we may derive your approximate location from other information about you, including your IP address.
    Information Collected from Other Sources
    We may receive information about you from other users or third parties, and combine that information with the other information we have about you.
    Linked services. If you authorize or link other services such as third-party API’s, Sandragon receives information about your previously purchased products from those services. Linking services may also cause the other service to send us information about your account with that service.
    Integrations. We also may receive information about you, including log and usage data and cookie information, from third-party websites that integrate our services, including our embeds, buttons, and advertising technology.
    <br><br><b>How Information About You Is Shared</b><br><br>
    When you use Sandragon services, certain information about you may be shared with other users and the public in the following ways:
    Submitted content: Content such as a post or comment or public chat to the services, may be viewed by any visitors to and users of our services, the username associated with the content, and the date and time you originally submitted the content. Sandragon may also allows third parties to access public content via google indexing. You should take this into consideration before posting to our services.
    Private messages or private chats: the recipients of those messages will be able to see the content of your message, your username, and the date and time the message was sent.
    Public Profiles: Users who view your public profile they will be able to see information about your activities on the services, such as your username, prior posts and comments, and how long you have been a member of the services.
    Please note that, even when you delete your account, the posts, comments and messages you submit through the services may still be viewable or available on our servers.
    Otherwise, we do not share, sell, or give away your personal information to third parties unless one of the following circumstances applies:
    Third Party Content Creators: If you link your account with a third-party API service, Sandragon will share the information you authorize with that third-party service.
    Partners: We may share information with vendors, consultants, and other service providers who need access to such information to carry out work for us. The partner’s use of personal data will be subject to appropriate confidentiality and security measures.
    Legal Disclosures: We may share information in response to a request for information if we believe disclosure is in accordance with, or required by, any applicable law, regulation, legal process or governmental request, including, but not limited to, meeting national security or law enforcement requirements. To the extent the law allows it, we will attempt to provide you with prior notice before disclosing your information in response to such a request.
    Emergencies: We may share information if we believe it's necessary to prevent imminent and serious bodily harm to a person.
    Enforcement of Our User Agreements: We may share information if we believe your actions are inconsistent with our user agreements, rules, or other policies, or to protect the rights, property, and safety of ourselves and others.
    Aggregated or de-identified information: We may share information about you that has been aggregated or anonymized such that it cannot reasonably be used to identify you.
    Advertisers: We may partner with third-party advertisers, ad networks, and analytics providers to deliver advertising and content targeted to your interests and to better understand your use of the services. These third parties may collect information sent by your computer, browser, or mobile device in response to a request for content, such as unique identifiers, your IP address, or other information about your computer or device.
    <br><br><b>Your Choices</b><br><br>
    As a user of our Services, you can take steps to limit our collection, use, and disclosure of your information.
    Accessing and Changing Your Information: You can change certain information through our services.
    Deleting Your Account: You may delete your account information at any time. You can also submit a request to delete the personal information Sandragon maintains. When you delete your account, your profile is no longer visible to other users.
    Linked Services’ Access to Your Account: You can review the services you have linked to your account and revoke access to individual services.
    Cookies: Most web browsers are set to accept cookies. You can choose to set your browser to remove or reject cookies.
    Advertising and Analytics: Some analytics providers we partner with may provide specific opt-out mechanisms and we may provide, as needed and as available, additional tools and third-party services that allow you to better understand cookies and how you can opt-out.
    Do Not Track: Most web browsers give you the option to send a Do Not Track signal to the websites you visit. However, there is no accepted standard for how a website should respond to this signal, and we do not take any action in response to this signal.
    Controlling Mobile Notifications: With your consent, we may send promotional and non-promotional push notifications or alerts to your mobile device. You can deactivate these messages at any time by changing the notification settings on your mobile device.
    Controlling Location Information: If you initially consent to our collection of location information, you can subsequently stop the collection of this information at any time by changing the preferences on your mobile device.
    <br><br><b>Miscellaneous</b><br><br>
    Information Security: We take measures to help protect information about you from loss, theft, misuse and unauthorized access, disclosure, alteration, and destruction. For
    Data Retention: We store the information we collect for as long as it is necessary for the purpose(s) for which we originally collected it. We may retain certain information for legitimate business purposes or as required by law.
    International Data Transfers: We are based in the United States and we process and store information on servers located in the United States. We may store information on servers and equipment in other countries depending on a variety of factors, including the locations of our users and service providers. By accessing or using the services or otherwise providing information to us, you consent to the processing, transfer and storage of information in and to the U.S. and other countries, where you may not have the same rights as you do under local law.
    In connection with processing of personal data received from the European Union and Switzerland, we make efforts to adhere to the EU-U.S. and Swiss-U.S. Privacy Shield Program (“Privacy Shield”) and comply with its framework and principles.
    Please direct any inquiries or complaints regarding our compliance with the Privacy Shield principles to the point of contact listed in the “Contact Us” section below. If we do not resolve your complaint, you may submit your complaint free of charge to JAMS. Under certain conditions specified by the Privacy Shield principles, you may also be able to invoke binding arbitration to resolve your complaint. We are subject to the investigatory and enforcement powers of the Federal Trade Commission. If we share EU or Swiss data with a third-party service provider that processes the data solely on our behalf, then we will be liable for that third party’s processing of EU or Swiss data in violation of the Privacy Shield principles, unless we can prove that we are not responsible for the event giving rise to the damage.
    Additional Information for EEA Users: Users in the European Economic Area have the right to request access to, rectification of, or erasure of their personal data; to data portability in certain circumstances; to request restriction of processing; to object to processing; and to withdraw consent for processing where they have previously provided consent. These rights can be exercised using the information provided under “Your Choices” above or by contacting us at the addresses provided below. EEA users also have the right to lodge a complaint with their local supervisory authority. As required by applicable law, we collect and process information about individuals in the EEA only where we have legal bases for doing so. Our legal bases depend on the Services you use and how you use them. We process your information on the following legal bases:
    You have consented for us to do so for a specific purpose;
    We need to process the information to provide you the Services, including to operate the Services, provide customer support and personalized features and to protect the safety and security of the Services;
    It satisfies a legitimate interest (which is not overridden by your data protection interests), such as preventing fraud, ensuring network and information security, enforcing our rules and policies, protecting our legal rights and interests, research and development, and marketing and promoting the Services;
    We need to process your information to comply with our legal obligations.
    Data Subject and Consumer Information Requests: Requests for a copy of the information Sandragon has about your account, including EU General Data Protection Regulation (GDPR) data subject access requests and California Consumer Privacy Act (CCPA) consumer information requests, can be submitted to the contact below.
    Children: Children under the age of 16 are not allowed to create an account or otherwise use the Services. Additionally, if you are in the EEA, you must be over the age required by the laws of your country to create an account or otherwise use the Services, or we need to have obtained verifiable consent from your parent or legal guardian.
    Changing This Policy: We may change this Privacy Policy from time to time. If we do, we will let you know by revising the date at the top of the policy. If we make a change to this policy that, in our sole discretion, is material, we will provide you with additional notice such as a banner on our site. We encourage you to review the Privacy Policy whenever you access or use our services or otherwise interact with us to stay informed about our information practices and the ways you can help protect your privacy. By continuing to use our services after Privacy Policy changes go into effect, you agree to be bound by the revised policy.
    Contact Us: To send a GDPR data subject request, CCPA consumer request, or if you have other questions about this Privacy Policy, please contact us at SandDragonGame@Gmail.com.

  </div>
</template>