<template>
    <div
      class="fixed rounded m-auto my-8 shadow"
      style="width: 50%; z-index: 4; background: white; transform: translate(50%, -15%); min-height: auto; overflow-y:scroll;">
      <div class="max-w-40 m-auto">
        <div class="p-10">
            Terms of Use<br>
            Effective September 1, 2020.
            Greetings Adventures! You find yourselves in a tavern with a particularly wordy barkeep who won’t let you in on your next treasure heist until he explains all the rules of the adventure. Your deception roll is a critical failure! Meaning that you cannot skip this discourse.
            Sandragon is a powerful platform uniting the world at your fingertips. The purpose of this platform is to have fun, and to ensure that people have fun, we have put together a few rules to keep things light and jovial.
            Access to the Platform
            Children under the age of sixteen are not allowed to create an account on Sandragon. This is meant to protect children from potential harms that can come to children from a platform that connects people from around the world. If you are accepting these Terms on behalf of another legal entity, including a business or a government, you represent that you have full legal authority to bind such entity to these terms.
            Use of the Platform
            By creating an account, Sandragon grants you a personal, non-transferable, non-exclusive, revocable, limited license to use and access the Sandragon services solely as permitted by these Terms. We reserve all rights not expressly granted to you by these this user agreement. Your license does not include the right to: license, sell, transfer, assign, distribute, host, or otherwise commercially exploit the Sandragon services or content; modify, prepare derivative works of, disassemble, decompile, or reverse engineer any part of Sandragon services or Content; or access Sandragon in order to build a similar or competitive website, product, or service. We reserve the right to modify, suspend, or discontinue Sandragon at any time, with or without notice to you. Any future release, update, or other addition to functionality of Sandragon will be subject to these Terms, which may be updated from time to time. You agree that we will not be liable to you or to any third party for any modification, suspension, or discontinuation of Sandragon or any part thereof.
            Account and Security
            To use certain features of Sandragon, you may be required to create an account and provide us with a username, password, and certain other information about yourself as set forth in the Privacy Policy. You are solely responsible for the information associated with the Account and anything that happens related to your Account. You must maintain the security of your Account and promptly notify us if you discover or suspect that someone has accessed your Account without your permission. We recommend that you use a strong password that is used only with Sandragon. You cannot license, sell, or transfer your Account without our prior written approval.
            Your Content
            You may provide Sandragon with content such as text, links, graphics, photos, videos, or other materials, including content created with or submitted to Sandragon by you or through your Account. We take no responsibility for and we do not expressly or implicitly endorse any of your Content. By submitting content to Sandragon, you represent and warrant that you have all rights, power, and authority necessary to grant the rights to the content contained within these Terms. Because you alone are responsible for your content, you may expose yourself to liability if you post or share content without all necessary rights. You retain any ownership rights you have in your content, but you grant Sandragon the following license to use that content:
            When your content is created with or submitted to the Sandragon, you grant us a worldwide, royalty-free, perpetual, irrevocable, non-exclusive, transferable, and sublicensable license to use, copy, modify, adapt, prepare derivative works from, distribute, perform, and display your content and any name, username, voice, or likeness provided in connection with your content in all media formats and channels now known or later developed. This license includes the right for us to make your content available for syndication, broadcast, distribution, or publication by other companies, organizations, or individuals who partner with us. You also agree that we may remove metadata associated with your content, and you irrevocably waive any claims and assertions of moral rights or attribution with respect to your content.
            Any ideas, suggestions, and feedback about Sandragon that you provide to us are entirely voluntary, and you agree that Sandragon may use such ideas, suggestions, and feedback without compensation or obligation to you. Although we have no obligation to screen, edit, or monitor your content, we may, in our sole discretion, delete or remove your content at any time and for any reason, including for a violation of these Terms, or if you otherwise create liability for us.
            Third-Party Content, Advertisements and Promotions
            Sandragon may contain links to third-party websites, products, or services, which may be posted by advertisers, our affiliates, our partners, or other users (“Third-Party Content”). Third-Party Content is not under our control, and we are not responsible for any of their websites, products, or services. Your use of Third-Party Content is at your own risk and you should make any investigation you feel necessary before proceeding with any transaction in connection with such Third-Party Content. Sandragon may also contain sponsored Third-Party Content or advertisements. The type, degree, and targeting of advertisements are subject to change, and you acknowledge and agree that we may place advertisements in connection with the display of any content or information on Sandragon, including your content. If you choose to use Sandragon to conduct a promotion, including a contest or sweepstakes, you alone are responsible for conducting the promotion in compliance with all applicable laws and regulations. The terms of your promotion must specifically state that the promotion is not sponsored by, endorsed by, or associated with Sandragon and the rules for your promotion must require each entrant or participant to release Sandragon from any liability related to the promotion.
            Things You Cannot Do
            When accessing or using Sandragon, you must respect others and their rights, including by following these Terms, so that we all may continue to use and enjoy Sandragon. When accessing or using our services, you will not: create or submit content that violates our policies or attempt to circumvent any content-filtering techniques we use; use Sandragon to violate applicable law or infringe any person or entity's intellectual property or any other proprietary rights; attempt to gain unauthorized access to another user’s Account or to Sandragon (or to other computer systems or networks connected to or used together with the Services); upload, transmit, or distribute to or through the Sandragon any computer viruses, worms, or other software intended to interfere with the intended operation of a computer system or data; use Sandragon to harvest, collect, gather or assemble information or data regarding Sandragon or users of the services except as permitted in these Terms or in a separate agreement with Sandragon; use Sandragon in any manner that could interfere with, disrupt, negatively affect, or inhibit other users from fully enjoying Sandragon or that could damage, disable, overburden, or impair the functioning of Sandragon in any manner; Intentionally negate any user's actions to delete or edit their Content; or Access, query, or search Sandragon with any automated system, other than through our published interfaces and pursuant to their applicable terms. However, we conditionally grant permission to crawl Sandragon for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials.
            Copyright, the DMCA & Takedowns
            Sandragon respects the intellectual property of others and requires that users of our services do the same. We have a policy that includes the removal of any infringing materials from the services and for the termination, in appropriate circumstances, of users of our services who are repeat infringers. If you believe that anything on Sandragon infringes a copyright that you own or control, you may notify Sandragon by email at sandragononline@gmail.com.
            Also, please note that if you knowingly misrepresent that any activity or material on our service is infringing, you may be liable to Sandragon for certain costs and damages. If we remove your content in response to a copyright or trademark notice, we will notify you via private messaging system. If you believe your content was wrongly removed due to a mistake or misidentification, you can send a counter notification to our email. Please see 17 U.S.C. §512(g)(3) for the requirements of a proper counter notification.
            Indemnity
            Except to the extent prohibited by law, you agree to defend, indemnify, and hold us, our licensors, our third party service providers and our officers, employees, licensors, and agents harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of Sandragon, (b) your violation of these Terms, (c) your violation of applicable laws or regulations, or (d) your content. We reserve the right to control the defense of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.
            Disclaimers
            THESE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SANDRAGON, ITS LICENSORS, AND ITS THIRD PARTY SERVICE PROVIDERS DO NOT WARRANT THAT THE SERVICES ARE ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR FREE. SANDRAGON DOES NOT CONTROL, ENDORSE, OR TAKE RESPONSIBILITY FOR ANY CONTENT AVAILABLE ON OR LINKED TO THE SERVICES OR THE ACTIONS OF ANY THIRD PARTY OR USER. WHILE SANDRAGON ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF OUR SERVICES SAFE, WE DO NOT REPRESENT OR WARRANT THAT OUR SERVICES OR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            Limitation of Liability
            IN NO EVENT AND UNDER NO THEORY OF LIABILITY, INCLUDING CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, WARRANTY, OR OTHERWISE, WILL THE SANDRAGON OR ITS PARTNERS, AGENTS, OR THIRD PARTIES BE LIABLE TO YOU FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, OR LOST PROFITS ARISING FROM OR RELATING TO THESE TERMS OR THE SERVICES, INCLUDING THOSE ARISING FROM OR RELATING TO CONTENT MADE AVAILABLE ON THE SERVICES THAT IS ALLEGED TO BE DEFAMATORY, OFFENSIVE, OR ILLEGAL. ACCESS TO, AND USE OF, THE SERVICES IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM. IN NO EVENT WILL THE AGGREGATE LIABILITY OF THE REDDIT ENTITIES EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS ($100) OR ANY AMOUNT YOU PAID SANDRAGON IN THE PREVIOUS SIX MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM. THE LIMITATIONS OF THIS SECTION WILL APPLY TO ANY THEORY OF LIABILITY, INCLUDING THOSE BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, AND EVEN IF THE SANDRAGON HAVE BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH DAMAGE, AND EVEN IF ANY REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED ITS ESSENTIAL PURPOSE. THE FOREGOING LIMITATION OF LIABILITY WILL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
            Governing Law and Venue
            We want you to enjoy Sandragon, so if you have an issue or dispute, you agree to raise it and try to resolve it with us informally. You can contact us with feedback and concerns here or by emailing us at sandragononline@gmail.com. Except for the government entities listed below: any claims arising out of or relating to these Terms or the Services will be governed by the laws of Virginia, other than its conflict of laws rules; all disputes related to these Terms or the Services will be brought solely in the federal or state courts located in Fairfax, Virginia; and you consent to personal jurisdiction in these courts. Government Entities: If you are a U.S. city, county, or state government entity, then this Section 13 does not apply to you. If you are a U.S. federal government entity: any claims arising out of or relating to these Terms or the Services will be governed by the laws of the United States of America without reference to conflict of laws. To the extent permitted by federal law, the laws of Virginia (other than its conflict of law rules) will apply in the absence of applicable federal law. All disputes related to these Terms or the Services will be brought solely in the federal or state courts located in Alexandria, Virginia.
            Changes to these Terms
            We may make changes to these Terms from time to time. If we make changes, we will post the amended Terms to our Services and update the Effective Date above. If the changes, in our sole discretion, are material, we may also notify you by sending an email to the address associated with your Account (if you have chosen to provide an email address) or by otherwise providing notice through our Services. By continuing to access or use Sandragon on or after the Effective Date of the revised Terms, you agree to be bound by the revised Terms. If you do not agree to the revised Terms, you must stop accessing and using our Services before the changes become effective.
            Termination
            You may terminate these Terms at any time and for any reason by deleting your Account and discontinuing your use of all of Sandragon’s services. If you stop using Sandragon without deactivating your Accounts, your Accounts may be deactivated due to prolonged inactivity. We may suspend or terminate your Accounts, or ability to access or use Sandragon at any time for any or no reason, including for a violation of these Terms. The following sections will survive any termination of these Terms or of your Accounts: 4 (Your Content), 6 (Things You Cannot Do), 10 (Indemnity), 11 (Disclaimers), 12 (Limitation of Liability), 13 (Governing Law and Venue), 16 (Termination), and 17 (Miscellaneous).
            Miscellaneous
            These Terms constitute the entire agreement between you and us regarding your access to and use of Sandragon. Our failure to exercise or enforce any right or provision of these Terms will not operate as a waiver of such right or provision. If any provision of these Terms is, for any reason, held to be illegal, invalid or unenforceable, the rest of the Terms will remain in effect. You may not assign or transfer any of your rights or obligations under these Terms without our consent. We may freely assign these Terms.
        </div>
      </div>
    </div>
</template>